<?php $this->headLink()->setStylesheet('/style/main.css'); ?>
<div class="content">
    <div id="splash" class="rounded"></div>
    <div id="login">
        <div class="form">
            <h1>Sign in</h1>
            <form id="WindowsAzureAccount" name="signin" action="<?php echo $this->url(array ('module' => 'default', 'controller' => 'index', 'action' => 'auth'), null, true) ?>" method="post">
                <dl id="azure_account_details">
                    <dt><label for="account_name">Account name:</label></dt>
                    <dd><input type="text" name="account_name" id="account_name" value="<?php echo $this->escape($this->account_name) ?>"></dd>
                    <dt><label for="account_key">Primary key:</label></dt>
                    <dd><input type="text" name="account_key" id="account_key" value="<?php echo $this->escape($this->account_key) ?>"></dd>
                    <dt><label for="remember_me">Remember me:</label></dt>
                    <dd><input type="checkbox" name="remember_me" id="remember_me" value="1" <?php echo (1 == $this->remember_me ? 'checked="checked"' : null) ?>></dd>
                    <dt>&nbsp;</dt>
                    <dd><input type="submit" value="Sign in"></dd>
                </dl>
            </form>

            <h2>Privacy</h2>
            <p>You're credentials are not kept, only stored in a session for the duration of your
            visit on the site. When checking "remember me" a cookie is stored on your local computer
            with your account details.</p>
            <h2>Windows Azure</h2>
            <p>This service only works on <strong>Windows Azure Blob Storage</strong> accounts. You
            can always suggest new features on our 
            <a href="http://github.com/PHPBenelux/azureblob/issues">Github issue list</a>.</p>
        </div>
    </div>
    <div class="clear">&nbsp;</div>
</div>