<?php $this->headTitle($this->translate('WASA Browser')) ?>
<?php $this->headScript()->appendFile($this->baseUrl('/jquery/js/jquery-1.8.0.min.js'))
                         ->appendFile($this->baseUrl('/jquery/js/jquery-ui-1.8.23.custom.min.js'))
                         ->appendFile($this->baseUrl('/jquery/development-bundle/ui/minified/jquery.ui.widget.min.js'))
                         ->appendFile($this->baseUrl('/jquery/plugins/File-Upload/js/jquery.iframe-transport.js'))
                         ->appendFile($this->baseUrl('/jquery/plugins/File-Upload/js/jquery.fileupload.js')); ?>
<?php $this->headLink()->prependStylesheet($this->baseUrl('/jquery/css/redmond/jquery-ui-1.8.23.custom.css')); ?>
<?php $this->headScript()->appendScript(<<<EOS

$(document).ready(function () {

    // Dialog
    $('#dialog').dialog({
        autoOpen: false,
        width: 600,
        modal: true,
        title: "Upload file(s) to {$this->lastContainer}",
        buttons: {
            "Ok": function() {
                $(this).dialog("close");
                document.location.href = '{$this->url(array ('module' => 'blob', 'controller' => 'index', 'action' => 'browse', 'container' => $this->lastContainer), null, true)}';
            },
            "Cancel": function() {
                $(this).dialog("close");
            }
        }
    });
    $('#preview').dialog({
        autoOpen: false,
        width: 600,
        modal: true
    });

    // open the dialog to upload files
    $('#addBlob').click(function () {
        $('#dialog').dialog('open');
        return false;
    });

    // prepare file upload settings
    $('#file').fileupload({
        dataType: 'json',
        done: function (e, data) {
            $.each(data.result, function (index, file) {
                $('<p/>').text(file.name).appendTo(document.body);
            });
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $( "#progressbar" ).progressbar({
                value: progress
            });
        }
    });
    
    $('.ui-icon-search').click(function () {
        console.log($(this).attr('href'));
        $('#preview').html('<img src="' + $(this).attr('href') + '" width="540"/>');
        $('#preview').dialog('open');
        return false;
    });

});

EOS
); ?>

<h1 class="pageTitle"><?php echo $this->translate('WASA Browser') ?></h1>

<div id="containerSwitchForm">
    <a class="floatLeft" href="<?php echo $this->url(array ('module' => 'blob', 'controller' => 'index', 'action' => 'container'), null, true) ?>" title="Overview of containers"><span class="ui-icon ui-icon-circle-arrow-w" style="display: inline-block">&lt;-</span></a>
    <form id="containerSwitch" action="<?php echo $this->url(array ('module' => 'blob', 'controller' => 'index', 'action' => 'browse'), null, true) ?>" method="GET">
        <select name="container" id="containerList">
        <?php foreach ($this->containers as $container): ?>
            <option value="<?php echo $container->getName() ?>" <?php echo ($container->getName() === $this->lastContainer ? 'selected="selected"' : null) ?>><?php echo $container->getName() ?></option>
        <?php endforeach; ?>
        </select>
        <input type="submit" value="Switch"/>
    </form>
</div>
<div id="addBlob" class="icon floatRight"><a id="addBlobLink" href="<?php echo $this->url(array ('module' => 'blob', 'controller' => 'index', 'action' => 'add-blob', 'container' => $this->lastContainer), null, true) ?>" title="Add a new Blob to this container"><span class="ui-icon ui-icon-circle-plus" style="display:inline-block;">+</span></a></div>

<div class="clear">&nbsp;</div>

<dl class="blobList">
    <dt class="title large metro_blue_fg metro_black_bg">File</dt>
    <dd class="title medium  metro_blue_fg metro_black_bg">Location</dd>
    <dd class="title small metro_blue_fg metro_black_bg">Content-type</dd>
    <dd class="title small metro_blue_fg metro_black_bg">Last modified</dd>
    <dd class="title metro_blue_fg metro_black_bg">Actions</dd>

<?php foreach ($this->blobs as $blob): ?>

    <dt class="data large"><?php echo $this->escape($this->substring($blob->getName())) ?></dt>
    <dd class="data medium"><a href="<?php echo $this->escape($blob->getUrl()) ?>" title="<?php echo $this->escape($blob->getUrl()) ?>"><?php echo $this->escape($this->substring($blob->getUrl())) ?></a></dd>
    <dd class="data small"><?php echo $blob->getProperties()->getContentType() ?></dd>
    <dd class="data small"><?php echo $blob->getProperties()->getLastModified()->format('Y-m-d H:i:s') ?></dd>
    <dd class="data center">
        <a href="<?php echo $this->url(array ('module' => 'blob', 'controller' => 'index', 'action' => 'remove-blob', 'file' => $blob->getName()), null, true) ?>" title="Remove <?php echo $this->escape($blob->getName()) ?>" onClick="return confirm('Are you sure you want to delete <?php echo $this->escape($blob->getName()) ?>?');"><span class="ui-icon ui-icon-circle-minus" style="display: inline-block">-</span></a>
        <?php if (strstr($blob->getProperties()->getContentType(), 'image/')): ?>
        <a href="<?php echo $this->escape($blob->getUrl()) ?>" class="ui-icon ui-icon-search"  style="display: inline-block">o</a>
        <?php endif; ?>
    </dd>
<?php endforeach; ?>

</dl>
<div class="clear">&nbsp;</div>

<div id="dialog">
    <form id="fileUpload" action="<?php echo $this->url(array ('module' => 'blob', 'controller' => 'index', 'action' => 'upload-blob')) ?>" method="post" enctype="multipart/form-data">
        <label for="file">File</label>
        <input type="file" name="file[]" id="file" multiple="multiple">
        <input type="submit" id="uploadBtn" value="Upload">
    </form>
    <br/>
    <div id="progressbar"></div>
</div>

<div id="preview"></div>