<?php $this->headTitle($this->translate('WATS for table "%s" and row "%s"', $this->table, $this->partition)) ?>

<?php $this->headScript()->appendFile($this->baseUrl('/jquery/js/jquery-1.8.0.min.js'))
                         ->appendFile($this->baseUrl('/jquery/js/jquery-ui-1.8.23.custom.min.js'))
                         ->appendFile($this->baseUrl('/jquery/development-bundle/ui/minified/jquery.ui.widget.min.js'))
                         ->appendFile($this->baseUrl('/jquery/plugins/File-Upload/js/jquery.iframe-transport.js'))
                         ->appendFile($this->baseUrl('/jquery/plugins/File-Upload/js/jquery.fileupload.js')); ?>
<?php $this->headLink()->prependStylesheet($this->baseUrl('/jquery/css/redmond/jquery-ui-1.8.23.custom.css')); ?>
<?php $this->headScript()->appendScript(<<<EOS

$(document).ready(function () {

    // Dialog
    $('#dialog').dialog({
        autoOpen: false,
        width: 600,
        modal: true,
        title: "Add a property to partition {$this->escape($this->table)}:{$this->escape($this->partition)}",
    });
    $('#preview').dialog({
        autoOpen: false,
        width: 600,
        modal: true
    });

    // open the dialog to upload files
    $('#addEntity').click(function () {
        $('#dialog').dialog('open');
        return false;
    });

});

EOS
); ?>

<h1 class="pageTitle"><?php echo $this->translate('WATS for table "%s" and row "%s"', $this->table, $this->partition) ?></h1>

<div id="containerSwitchForm">
    <a class="floatLeft" href="<?php echo $this->url(array ('module' => 'table', 'controller' => 'index', 'action' => 'browse', 'table' => $this->table), null, true) ?>" title="Overview of containers"><span class="ui-icon ui-icon-circle-arrow-w" style="display: inline-block">&lt;-</span></a>
</div>
<div id="addEntity" class="icon floatRight"><a id="addEntityLink" href="<?php echo $this->url(array ('module' => 'table', 'controller' => 'index', 'action' => 'add-entity', 'table' => $this->table), null, true) ?>" title="Add a new Entity to this table"><span class="ui-icon ui-icon-circle-plus" style="display:inline-block;">+</span></a></div>

<div class="clear">&nbsp;</div>

<dl class="blobList">
    <dt class="title large metro_blue_fg metro_black_bg">Property key</dt>
    <dd class="title medium  metro_blue_fg metro_black_bg">Type</dd>
    <dd class="title medium  metro_blue_fg metro_black_bg">Value</dd>
    <dd class="title metro_blue_fg metro_black_bg">Actions</dd>

<?php foreach ($this->entity->getProperties() as $key => $property): ?>

    <dt class="data large"><?php echo $this->escape($key) ?></dt>
    <dd class="data medium"><?php echo $this->escape($property->getEdmType()?: 'Edm.String') ?></dd>
    <dd class="data medium"><?php echo $this->escape('Edm.DateTime' === $property->getEdmType() ? $property->getValue()->format('Y-m-d H:i:s') : $property->getValue()) ?></dd>
    <dd class="data center">
        <a href="<?php echo $this->url(array ('module' => 'table', 'controller' => 'index', 'action' => 'remove-entity', 'table' => $this->table, 'partition' => $this->entity->getPartitionKey(), 'row' => $this->entity->getRowKey()), null, true) ?>" title="Remove <?php echo $this->escape($this->entity->getPartitionKey()) ?>" onClick="return confirm('Are you sure you want to delete <?php echo $this->escape($this->entity->getPartitionKey()) ?>?');"><span class="ui-icon ui-icon-circle-minus" style="display: inline-block">-</span></a>
    </dd>
<?php endforeach; ?>

</dl>
<div class="clear">&nbsp;</div>

<div id="dialog">
    <div id="propertyForm"style="text-align: left;">
        <form id="entityForm" action="<?php echo $this->url(array (
            'module' => 'table',
            'controller' => 'index',
            'action' => 'create-entity',
        ), null, true) ?>" method="post">
            <label for="propertyKey">PropertyKey</label>:
            <input type="text" name="propertyKey" id="propertyKey"/><br/>
            <label for="propertyType">PropertyType</label>:
            <select name="propertyType" id="propertyType">
                <?php foreach ($this->propertyTypes as $propertyTypeValue => $propertyTypeText): ?>
                <option value="<?php echo $this->escape($propertyTypeValue) ?>"><?php echo $this->escape($propertyTypeText) ?></option>
                <?php endforeach; ?>
            </select><br/>
            <label for="value">Value</label>:
            <input type="text" name="value" id="value"/><br/>
            <input type="hidden" name="table" value="<?php echo $this->escape($this->table) ?>"/>
            <input type="hidden" name="partition" value="<?php echo $this->escape($this->partition) ?>"/>
            <input type="submit" value="Add entity"/>
        </form>
    </div>
</div>
